version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - neo4j_db
    networks:
      - app_network
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - NEO4J_URI=bolt://neo4j_db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test

 
  neo4j_db:
    image: neo4j:latest
    container_name: neo4j_db
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/test  
    ports:
      - "7474:7474"  # Neo4j Dashboard
      - "7687:7687"  # Conexión a la base de datos
    volumes:
      - neo4j_data:/data
      - ./neo4j/import:/import  # Permite importar CSV u otros archivos
    networks:
      - app_network
  db:
    image: postgres:13
    restart: always
    ports:
      -5332:5332
    environment:
      POSTGRES_PASSWORD: test
  admin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      -80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: Jhonaatan.baron@uptc.edu.co
      PGADMIN_DEFAULT_PASSWORD: test


volumes:
  neo4j_data:

networks:
  app_network:
    driver: bridge
